(function(){window.easyInline=function(){function i(){try{if(l==!0)b.style.width="1px",b.style.height="1px",b.style.left="-1000px",b.style.top="-1000px",l=!1}catch(a){e("hideSwf: "+a)}}function e(a){try{s==!0?typeof console!="undefined"&&console.log("debug: "+a):easyInline.track("debug: "+a)}catch(e){}}function C(){try{var a="";document.selection?a=document.selection.createRange().text:document.getSelection&&(a=document.getSelection().toString());if(a){var b;try{b=a.replace(/(^|[^\\])'/g,"$1\\'")}catch(c){e("escapeQuotes "+
c)}finally{}var d;try{d=b.replace(/(^\s*)|(\s*$)/gi,""),d=d.replace(/[ ]{2,}/gi," "),d=d.replace(/\n /,"\n")}catch(g){e("removeWhiteSpace "+g)}finally{a=d}}}catch(f){}finally{return a||""}}function D(a){try{var b=!1,c;a:{try{var d=a||window.event,a=null;d&&(a=d.target==null?d.srcElement:d.target);c=a;break a}catch(g){e("getEventTarget: "+g)}c=void 0}if(c&&typeof c.nodeName!="undefined"){var f;try{d=!0;for(a=0;a<p.length;a++)if(c.nodeName==p[a]){d=!1;break}}catch(i){e("isValidNodeName "+i)}finally{f=
d}f&&(b=!0)}}catch(j){e("isValidTarget "+j)}finally{return b}}function q(){try{l==!0&&i()}catch(a){e("handleResize: "+a)}}function v(){try{var a=document.onmouseup;document.onmouseup=function(c){var d,h;a:try{if(E&&D(c)){g=C();var f;if(f=g)b:{try{if(g){f=g.length<G;break b}}catch(k){e("doesNotExceedMaxChars "+k)}f=void 0}if(f){try{if(g=C(),f=g==w,g&&!f){w=g;try{try{var j=f=0,r=((window.innerWidth||document.documentElement.offsetWidth)-document.body.clientWidth)/2,o;try{x==null&&(x=window.navigator.appName.indexOf("Microsoft")>
-1),o=x}catch(t){}if(o){var y=c||window.event;y&&(f=y.clientX+document.documentElement.scrollLeft,j=y.clientY+document.documentElement.scrollTop)}else f=c.pageX,j=c.pageY;f-=r;f<0&&(f=0);j<0&&(j=0)}catch(s){e("getMousePosition: "+s)}finally{d=f,h=j}h+=F;try{if(l==!1)b.style.width=z,b.style.height=A,l=!0;var m;try{var r={x:d,y:h},p=parseInt(b.style.width),q=parseInt(b.style.height),u=window.innerHeight||document.documentElement.offsetHeight;d+p>(window.innerWidth||document.documentElement.offsetWidth)&&
(r.x-=p);h+q>u&&(r.y-=q*2-F)}catch(v){e("checkContainerPosition: "+v)}finally{m=r}b.style.left=m.x+"px";b.style.top=m.y+"px"}catch(H){e("showSwf: "+H)}m=g;try{if(m){if(n==null||n.nodeName!="OBJECT")n=document.getElementById(B);n?typeof n.setTextSelection=="function"&&n.setTextSelection(m):i()}}catch(I){e("callSwf: "+I)}}catch(J){e("handleTextSelection "+J)}}else w=g,i()}catch(K){e("checkSelection "+K)}break a}}setTimeout(i,0)}catch(L){}finally{}typeof a=="function"&&a(c)};a=document.onmousedown;document.onmousedown=
function(c){try{E=D(c)}catch(d){}typeof a=="function"&&a(c)};a=document.onkeydown;document.onkeydown=function(c){try{i()}catch(d){}typeof a=="function"&&a(c)};window.addEventListener?window.addEventListener("resize",q,!1):window.attachEvent&&window.attachEvent("onresize",q)}catch(h){e("addEventListeners "+h)}}var x=null,n,B="easyInlineSwf",o,z="150px",A="20px",k,b,s=!1,g="",l=!0,E=!1,F=12,w="",t=null,G=256,p="BUTTON,A,INPUT,OBJECT,TEXTAREA,SELECT,OPTION".split(","),u=!1;return{supportUrl:"http://www.easyinline.com/support",
productName:"EasyInline",baseUrl:"http://edge.easyinline.com",init:function(){try{if(u==!1){easyInline.getUserId();try{b=document.createElement("div"),b.style.position="absolute",b.style.zIndex="2147483647",o=document.createElement("div"),o.id=B,b.appendChild(o),document.body.appendChild(b)}catch(a){e("createContainer: "+a)}try{var h={supportUrl:easyInline.supportUrl,baseUrl:easyInline.baseUrl,productName:easyInline.productName};typeof k=="undefined"&&(k=easyInline.getSwfObject());k.embedSWF(easyInline.baseUrl+
"/app/easyInline.swf",B,"100%","100%","10.0.0","expressInstall.swf",h,{menu:"false",allowScriptAccess:"always",wmode:"transparent"},{style:"outline:none;"})}catch(c){e("loadSwf: "+c)}l=!0;i();v();u=!0}}catch(d){e("init: "+d)}},resize:function(a,h){try{z=a+"px",A=h+"px",b.style.width=z,b.style.height=A}catch(c){e("resize: "+c)}},track:function(a){try{var b,c;try{t!=!0&&(t=typeof mixpanel!="undefined"&&s==!1&&!1)}catch(d){e("checkTrackingConditions "+d)}finally{c=t}if(b=c)try{c=!1,Math.random()<0.01&&
(c=!0)}catch(g){e("checkSampling "+g)}finally{b=c}b&&(mixpanel.easyinline||mixpanel.init("72366557fd3f1bd4fc7d4bfca5cd0a12",{},"easyinline"),mixpanel.easyinline.track(a))}catch(f){}},actionComplete:function(){try{setTimeout(i,10)}catch(a){e("actionComplete: "+a)}},getSwfObject:function(){try{return k||window.swfobject||YontooClient.swfobject}catch(a){}},setSwfObject:function(a){try{k=a}catch(b){}},getUserId:function(){return 0}}}()})();
